name: beadles_app_prototype1
description: "Beadles App Prototype 1"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  loading_animation_widget:
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

assets:
  - assets/images/
  - assets/icons/
  - assets/logo/

flutter:
  uses-material-design: true
